### ISSUE TITLE
Documentation for Java Sample Code

### ISSUE THREAD

**Issue by ergozeller** [SmartgridReady/SGrJavaSamples#1]
# Requirement
A new reader should be able to setup SGrJavSamples within 4 hours with reading the readme file.

- [x] Java documented
- [x] Readme File written
- [x] Illustrating graphis
- [x] Sample Code for various typical situations

**Comment by ergozeller** [comment]
Hi Michel,
Bitte die Grafik bzw. Readme anpassen mit den Themen wie gestern besprochen:
- [ ] Software läuft im Communicator (ggf. eine Gerätebox um die oberen Komponenten bis und mit Transport Layer)
- [ ] External Interface verändert das Produkt nicht (Vorschlag: external Interface innerhalb des Produkts plazierne mit gleicher Farbe wie das Produkt)

**Comment by ergozeller** [comment]
Hi Hans
Wie weit bist Du schon? Kannst Du einzelnen Tasks schon abhacken?

**Comment by ergo-furrer** [comment]
Hi Simon
Die ersten 3 Punkte sind soweit erledigt. Ich habs schon auf master committed. Ich plane das Ganze nochmals durchzugehen und allenfalls Korrekturen anzubringen.

Gruss Hans
