### ISSUE TITLE
Update dependency versions for to 1.1.0 for commhandler and sgr-drivers

### ISSUE THREAD

**Issue by ergo-furrer** [SmartgridReady/SGrJavaSamples#6]

**Comment by mkrebs81** [comment]
is it OK if I create new samples based on the new release in a separate branch based on this PR?

**Comment by ergo-furrer** [comment]
Thanks. That the would be nice.

**Comment by mkrebs81** [comment]
I adapted the examples and added a new example which uses the SGrDeviceBuilder.
